# Generated by Django 4.2.7 on 2025-08-01 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('compatible', 'Compatible'), ('conditional', 'Conditional/Uncertain'), ('incompatible', 'Incompatible')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence level from 0.0 to 1.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('base_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.compatibilitylink')),
                ('component_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_a', to='components.component')),
                ('component_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_b', to='components.component')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='compatibili_status_37cc21_idx'), models.Index(fields=['confidence'], name='compatibili_confide_8c2ac3_idx'), models.Index(fields=['is_active'], name='compatibili_is_acti_7c7519_idx')],
                'unique_together': {('component_a', 'component_b')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_status', models.CharField(choices=[('compatible', 'Compatible'), ('conditional', 'Conditional/Uncertain'), ('incompatible', 'Incompatible')], max_length=20)),
                ('result_confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('result_explanation', models.TextField()),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_a', to='components.component')),
                ('component_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_b', to='components.component')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='compatibili_created_1ae1a4_idx'), models.Index(fields=['result_status'], name='compatibili_result__e37e39_idx')],
            },
        ),
    ]
