version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: compatibility_db
    environment:
      POSTGRES_DB: compatibility_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - compatibility_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: compatibility_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - compatibility_network

  # Django Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: compatibility_backend
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/compatibility_system
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - compatibility_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: compatibility_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - compatibility_network

  # AI Scraping Service
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: compatibility_scraper
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/compatibility_system
      - REDIS_URL=redis://redis:6379/1
      - SCRAPER_SCHEDULE=0 2 * * *  # Daily at 2 AM
    volumes:
      - ./scraper:/app
      - scraper_logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - compatibility_network

volumes:
  postgres_data:
  redis_data:
  media_files:
  scraper_logs:

networks:
  compatibility_network:
    driver: bridge