# Generated by Django 4.2.7 on 2025-08-01 23:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('crankset', 'Crankset'), ('cassette', 'Cassette'), ('derailleur', 'Derailleur'), ('brakes', 'Brakes'), ('frame', 'Frame'), ('shifter', 'Shifter'), ('chain', 'Chain'), ('wheel', 'Wheel')], max_length=50)),
                ('speed', models.IntegerField(blank=True, help_text='e.g., 11, 12 for speed count', null=True)),
                ('specs', models.JSONField(default=dict, help_text='JSON specifications for compatibility')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'components_component',
                'ordering': ['brand', 'model'],
                'indexes': [models.Index(fields=['brand'], name='components__brand_b62b47_idx'), models.Index(fields=['type'], name='components__type_3292eb_idx'), models.Index(fields=['speed'], name='components__speed_7453e0_idx')],
                'unique_together': {('brand', 'model', 'type')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cassette_driver', 'Cassette to Driver Body'), ('shifter_derailleur', 'Shifter to Derailleur'), ('derailleur_cassette', 'Derailleur to Cassette'), ('brake_lever', 'Brake to Lever'), ('crankset_bb', 'Crankset to Bottom Bracket'), ('chain_cassette', 'Chain to Cassette'), ('wheel_frame', 'Wheel to Frame')], max_length=50)),
                ('status', models.CharField(choices=[('compatible', 'Compatible'), ('compatible_with_adapter', 'Compatible with Adapter'), ('not_compatible', 'Not Compatible')], max_length=30)),
                ('adapter_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='components.component')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='components.component')),
            ],
            options={
                'db_table': 'compatibility_link',
                'indexes': [models.Index(fields=['source'], name='compatibili_source__61b08b_idx'), models.Index(fields=['target'], name='compatibili_target__48c39b_idx'), models.Index(fields=['status'], name='compatibili_status_417688_idx')],
                'unique_together': {('source', 'target', 'type')},
            },
        ),
    ]
