# Generated by Django 4.2.7 on 2025-08-01 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_type', models.CharField(choices=[('road', 'Road'), ('mountain', 'Mountain'), ('gravel', 'Gravel'), ('cyclocross', 'Cyclocross'), ('hybrid', 'Hybrid'), ('bmx', 'BMX'), ('track', 'Track')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2030)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.OneToOneField(limit_choices_to={'type': 'frame'}, on_delete=django.db.models.deletion.CASCADE, related_name='frame_metadata', to='components.component')),
            ],
            options={
                'ordering': ['component__brand', 'component__model', 'year'],
            },
        ),
    ]
