# Generated by Django 4.2.7 on 2025-08-01 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('bottom_bracket', 'Bottom Bracket'), ('axle', 'Axle Standard'), ('brake_mount', 'Brake Mount'), ('headtube', 'Headtube'), ('seatpost', 'Seatpost'), ('cassette', 'Cassette'), ('chain', 'Chain'), ('driver_body', 'Driver Body'), ('mount_type', 'Mount Type')], max_length=50)),
                ('description', models.TextField()),
                ('specifications', models.JSONField(default=dict)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thread_pitch', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='standards_s_categor_b81703_idx'), models.Index(fields=['is_active'], name='standards_s_is_acti_42e3f9_idx')],
            },
        ),
    ]
